routes/web.php
<?php


Auth::routes();

Route::namespace('user')->group(function () {

    Route::get('/', 'homeController@index')->name('user.home');

    Route::group(['prefix' => 'profilDesa', 'as' => 'profilDesa.'], function () {
        Route::get('/', 'profilDesaController@index')->name('index');

    });

    Route::group(['prefix' => 'galery', 'as' => 'galery.'], function () {
        Route::get('/', 'galeryController@index')->name('index');

    });
    
    Route::group(['prefix' => 'wisata', 'as' => 'wisata.'], function () {
        Route::get('/', 'wisataController@index')->name('index');


    });

    Route::group(['prefix' => 'wirausaha', 'as' => 'wirausaha.'], function () {
        Route::get('/', 'wirausahaController@index')->name('index');


    });

    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
        Route::get('/', 'blogController@index')->name('index');


    });

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');

Route::namespace('admin')->middleware('auth:admin')->group(function () {

    Route::get('/adminHome', 'homeController@index')->name('admin.home');

    Route::group(['prefix' => 'galeryAdmin', 'as' => 'galeryAdmin.'], function () {

        Route::get('/', 'galeryController@index')->name('index');
        Route::post('/store', 'galeryController@store')->name('store');
        Route::post('{galeryAdmin}/update', 'galeryController@update')->name('update');
        Route::post('{galeryAdmin}/delete', 'galeryController@delete')->name('delete');


    });

    Route::group(['prefix' => 'wisataAdmin', 'as' => 'wisataAdmin.'], function () {

        Route::get('/', 'wisataController@index')->name('index');
        Route::post('/store', 'wisataController@store')->name('store');
        Route::post('{wisataAdmin}/update', 'wisataController@update')->name('update');
        Route::post('{wisataAdmin}/delete', 'wisataController@delete')->name('delete');


    });

    Route::group(['prefix' => 'wirausahaAdmin', 'as' => 'wirausahaAdmin.'], function () {

        Route::get('/', 'wirausahaController@index')->name('index');
        Route::post('/store', 'wirausahaController@store')->name('store');
        Route::post('{wirausahaAdmin}/update', 'wirausahaController@update')->name('update');
        Route::post('{wirausahaAdmin}/delete', 'wirausahaController@delete')->name('delete');


    });

    Route::group(['prefix' => 'ubahPasswordAdmin', 'as' => 'ubahPasswordAdmin.'], function () {

        Route::get('/', 'ubahPasswordAdminController@index')->name('index');
        Route::post('{userAdmin}/update', 'ubahPasswordAdminController@update')->name('update');


    });


});

app/Models/Wirausaha.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\Wirausaha as Authenticatable;
use Illuminate\Support\Facades\Hash;

class Wirausaha extends Model{

    protected $fillable = [
        'foto','namaWirausaha', 'deskripsi',
        
    ];
}

app/Http/Controllers/admin/wirausahaController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Wirausaha;
use App\Repositories\WirausahaRepository;
use File;


class wirausahaController extends Controller{

    private $WirausahaRepository;

    public function __construct(WirausahaRepository $WirausahaRepository){

        $this->WirausahaRepository = $WirausahaRepository;

    }
   
    public function index(Request $request){

        $page = $request->get('page', 1);
        $limit = 10;

        $wirausaha = $this->WirausahaRepository->get($limit);
        $data = [
            'no' => ($page - 1) * $limit,
            'wirausaha' => $wirausaha
        ];
        return view('admin/wirausaha/index',$data);

    }

    public function store(Request $request){

        $validate = [
            'foto' => 'required|image|mimes:jpeg,png,jpg',
            'namaWirausaha' => 'required|max:100',
            'deskripsi' => 'required|max:255',
          
        ];
        
        $this->validate(request(), $validate);
        $image = $request->file('foto');
        $imageName = $image->getClientOriginalName();
        $image->move(public_path('assets/images/wirausaha'), $imageName);
        $detail = new Wirausaha();
        $detail->namaWirausaha = $request->get('namaWirausaha');
        $detail->deskripsi = $request->get('deskripsi');
        $detail->foto = $imageName;
        $detail->save();
        return redirect()->route('wirausahaAdmin.index')->with('success', 'Successfully created.');

    }

    public function update(Request $request, $id){
        $detail = Wirausaha::where('id', $id)->first();
        
        $validate = [
            'foto' => 'required|image|mimes:jpeg,png,jpg',
            'namaWirausaha' => 'required|max:255',
            'deskripsi' => 'required|max:255',
          
        ];

        $image = $request->file('foto');

        if($image == null){
            $imageName = $detail->foto;
            
        }else {
            $image_path = public_path('assets/images/wirausaha/'.$detail->foto);
            if (File::exists($image_path)) {
                unlink($image_path);
            }
            $imageName = $image->getClientOriginalName();
            $image->move(public_path('assets/images/wirausaha'), $imageName);
        }

        $detail->namaWirausaha = $request->get('namaWirausaha');
        $detail->deskripsi = $request->get('deskripsi');
        $detail->foto = $imageName;
        $detail->save();
        \Session::flash('notif-success', 'Update data berhasil');
        return redirect()->route('wirausahaAdmin.index')->with('success', 'Successfully created.');

    }

    public function delete($id){
        $detail = Wirausaha::where('id', $id)->first();
        $image_path = public_path('assets/images/wirausaha/'.$detail->foto);

        if(!$detail){
            \Session::flash('notif-error', 'Data tidak ditemukan');
            return redirect(route('wirausahaAdmin.index'));
        }

        if (File::exists($image_path)) {
            unlink($image_path);
        }

        $detail->delete();

        \Session::flash('notif-success', 'Data berhasil dihapus');
        return redirect()->route('wirausahaAdmin.index')->with('success', 'Designations successfully deleted.');
    }
}

app/Http/Controllers/user/wirausahaController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Wirausaha;
use App\Repositories\WirausahaRepository;

class wirausahaController extends Controller{

    private $WirausahaRepository;

    public function __construct(WirausahaRepository $WirausahaRepository){

        $this->WirausahaRepository = $WirausahaRepository;

    }

    public function index(Request $request){

        $page = $request->get('page', 1);
        $limit = 10;

        $wirausaha = $this->WirausahaRepository->get($limit);
        $data = [
            'no' => ($page - 1) * $limit,
            'wirausaha' => $wirausaha
        ];

        return view('user/wirausaha/index',$data);

    }
}

resources/views/admin/wirausaha/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="right_col" role="main">
    <div class="">
    	<div class="page-title">
        	<div class="title_left">
                <h3> Wirausaha Sidomulyo</h3>
            </div>
        </div>
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-12">
            	<div class="x_panel">
                	<div class="x_title">
                    <button style="margin-left:970px;" type="button" class="btn btn-primary" data-toggle="modal" data-target="#tambah">Tambah</button>
                        <div class="clearfix"></div>
                    </div>
                    <div class="modal fade" id="tambah" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form role="form" method="POST" action="{{route('wirausahaAdmin.store')}}" enctype="multipart/form-data">
                                    {{ csrf_field() }}
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Tambah Wirausaha</h5>
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="foto">Foto</label>
                                            <input type="file" class="form-control-file" id="foto" name="foto">
                                        </div>
                                        <div class="form-group">
                                            <label for="namaWirausaha">Nama Wirausaha</label>
                                            <input type="text" class="form-control" id="namaWirausaha" placeholder="Nama Wirausaha" name="namaWirausaha">
                                        </div>
                                        <div class="form-group">
                                            <label for="deskripsi">Deskripsi</label>
                                            <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3"></textarea>
                                        </div>       
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                        <button type="submit" class="btn btn-primary">Simpan</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="x_content">
                        <div class="row">
                        @foreach ($wirausaha as $key => $wirausahaa)
                            <div class="col-md-55">
                                <div class="thumbnail">
                                    <div class="image view view-first">
                                        <img style="width: 100%; display: block;" src="{{asset('assets/images/wirausaha/'.$wirausahaa->foto)}}" alt="image" />
                                        <div class="mask">
                                            <p>{{ $wirausahaa->namaWirausaha }}</p>
                                            <div class="tools tools-bottom">
                                                <form action="{{route('wirausahaAdmin.delete', $wirausahaa->id)}}" method="POST" style="display: inline-block;">
                                                    {{ csrf_field() }}
                                                    <a data-toggle="modal" data-target="#ubah{{ $wirausahaa->id }}" class="btn btn-primary btn-xs">ubah</a>
                                                    <button class="btn btn-danger" onclick="return confirm('Delete?')">HAPUS</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="caption">
                                        <p>{{ $wirausahaa->deskripsi }}</p>
                                    </div>
                                </div>
                            </div>
                            <div class="modal fade" id="ubah{{ $wirausahaa->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <form role="form" method="POST" action="{{route('wirausahaAdmin.update',$wirausahaa->id)}}" enctype="multipart/form-data">
                                        {{ csrf_field() }}
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Ubah Wirausaha</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <label for="foto">Foto</label>
                                                    <input type="file" class="form-control-file" id="foto" name="foto">
                                                </div>
                                                <div class="form-group">
                                                    <label for="namaWirausaha">Nama Wisata</label>
                                                    <textarea class="form-control" id="namaWirausaha" name="namaWirausaha" rows="1" placeholder="Nama Dusun" required>{{ $wirausahaa->namaWirausaha }}</textarea>
                                                </div>
                                                <div class="form-group">
                                                    <label for="deskripsi">Deskripsi</label>
                                                    <textarea class="form-control" id="deskripsi" name="deskripsi" rows="3" placeholder="Deskripsi" required>{{ $wirausahaa->deskripsi }}</textarea>
                                                </div>       
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                                                <button type="submit" class="btn btn-primary">Simpan</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            @endforeach
                        </div>
                        {{ $wirausaha->links() }}
                    </div>
        	    </div>
    	    </div>
        </div>
    </div>
</div>
@endsection