routes/web.php
<?php


Auth::routes();

Route::namespace('user')->group(function () {

    Route::get('/', 'homeController@index')->name('user.home');

    Route::group(['prefix' => 'profilDesa', 'as' => 'profilDesa.'], function () {
        Route::get('/', 'profilDesaController@index')->name('index');

    });

    Route::group(['prefix' => 'galery', 'as' => 'galery.'], function () {
        Route::get('/', 'galeryController@index')->name('index');

    });
    
    Route::group(['prefix' => 'wisata', 'as' => 'wisata.'], function () {
        Route::get('/', 'wisataController@index')->name('index');


    });

    Route::group(['prefix' => 'wirausaha', 'as' => 'wirausaha.'], function () {
        Route::get('/', 'wirausahaController@index')->name('index');


    });

    Route::group(['prefix' => 'blog', 'as' => 'blog.'], function () {
        Route::get('/', 'blogController@index')->name('index');


    });

});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/login/admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('/login/admin', 'Auth\LoginController@adminLogin');

Route::namespace('admin')->middleware('auth:admin')->group(function () {

    Route::get('/adminHome', 'homeController@index')->name('admin.home');

    Route::group(['prefix' => 'galeryAdmin', 'as' => 'galeryAdmin.'], function () {

        Route::get('/', 'galeryController@index')->name('index');
        Route::post('/store', 'galeryController@store')->name('store');
        Route::post('{galeryAdmin}/update', 'galeryController@update')->name('update');
        Route::post('{galeryAdmin}/delete', 'galeryController@delete')->name('delete');


    });

    Route::group(['prefix' => 'wisataAdmin', 'as' => 'wisataAdmin.'], function () {

        Route::get('/', 'wisataController@index')->name('index');
        Route::post('/store', 'wisataController@store')->name('store');
        Route::post('{wisataAdmin}/update', 'wisataController@update')->name('update');
        Route::post('{wisataAdmin}/delete', 'wisataController@delete')->name('delete');


    });

    Route::group(['prefix' => 'wirausahaAdmin', 'as' => 'wirausahaAdmin.'], function () {

        Route::get('/', 'wirausahaController@index')->name('index');
        Route::post('/store', 'wirausahaController@store')->name('store');
        Route::post('{wirausahaAdmin}/update', 'wirausahaController@update')->name('update');
        Route::post('{wirausahaAdmin}/delete', 'wirausahaController@delete')->name('delete');


    });

    Route::group(['prefix' => 'ubahPasswordAdmin', 'as' => 'ubahPasswordAdmin.'], function () {

        Route::get('/', 'ubahPasswordAdminController@index')->name('index');
        Route::post('{userAdmin}/update', 'ubahPasswordAdminController@update')->name('update');


    });


});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/user/blogController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class blogController extends Controller{

    public function index(){
        return view('user/blog/index');

    }

    public function create(){
        

    }

    public function store(Request $request){
        

    }

    public function show($id){
        

    }

    public function edit($id){
        

    }

    public function update(Request $request, $id){
        

    }

    public function destroy($id){
        
        
    }
}

app/Http/Controllers/user/galeryController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Galery;
use App\Repositories\GaleryRepository;

class galeryController extends Controller{

    private $GaleryRepository;

    public function __construct(GaleryRepository $GaleryRepository){

        $this->GaleryRepository = $GaleryRepository;

    }

    public function index(Request $request){

        $page = $request->get('page', 1);
        $limit = 10;

        $galery = $this->GaleryRepository->get($limit);
        $data = [
            'no' => ($page - 1) * $limit,
            'galery' => $galery
        ];

        return view('user/galery/index',$data);
    
    }
}

app/Http/Controllers/user/homeController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Galery;
use App\Repositories\GaleryRepository;

class homeController extends Controller{

    private $GaleryRepository;

    public function __construct(GaleryRepository $GaleryRepository){

        $this->GaleryRepository = $GaleryRepository;

    }
 
    public function index(Request $request){
        $page = $request->get('page', 1);
        $limit = 10;

        $galery = $this->GaleryRepository->get($limit);
        $data = [
            'no' => ($page - 1) * $limit,
            'galery' => $galery
        ];

       return view ('user/home/index',$data);
        
    }

    public function create(){
        

    }

    public function store(Request $request){

       
    }

    public function show($id){
        

    }

    public function edit($id){
        

    }

    public function update(Request $request, $id){
        

    }

    public function destroy($id){
        

    }
}

app/Http/Controllers/user/profilDesaController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class profilDesaController extends Controller{
 
    public function index(){
        return view('user/profil/index');

    }

    public function create(){
        

    }

    public function store(Request $request){
        

    }

    public function show($id){
        

    }

    public function edit($id){
        

    }

    public function update(Request $request, $id){
        

    }

    public function destroy($id){
        

    }
}

app/Http/Controllers/user/wirausahaController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Wirausaha;
use App\Repositories\WirausahaRepository;

class wirausahaController extends Controller{

    private $WirausahaRepository;

    public function __construct(WirausahaRepository $WirausahaRepository){

        $this->WirausahaRepository = $WirausahaRepository;

    }

    public function index(Request $request){

        $page = $request->get('page', 1);
        $limit = 10;

        $wirausaha = $this->WirausahaRepository->get($limit);
        $data = [
            'no' => ($page - 1) * $limit,
            'wirausaha' => $wirausaha
        ];

        return view('user/wirausaha/index',$data);

    }
}

app/Http/Controllers/user/wisataController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Wisata;
use App\Repositories\WisataRepository;


class wisataController extends Controller{

    private $WisataRepository;

    public function __construct(WisataRepository $WisataRepository){

        $this->WisataRepository = $WisataRepository;

    }
  
    public function index(Request $request){
        $page = $request->get('page', 1);
        $limit = 10;

        $wisata = $this->WisataRepository->get($limit);
        $data = [
            'no' => ($page - 1) * $limit,
            'wisata' => $wisata
        ];

        return view('user/wisata/index',$data);

    }

    public function create(){
        

    }

    public function store(Request $request){
        

    }

    public function show($id){
        

    }

    public function edit($id){
        

    }

    public function update(Request $request, $id){
        

    }

    public function destroy($id){
        
        
    }
}

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="right_col" role="main">
    <div class="">
        <div class="page-title">
            <div class="title_left">
                <h3>Ganti Password</h3>
            </div>
            <div class="clearfix"></div>
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="x_panel">
                            <div class="x_content">
                                <br />  
                                @foreach ($user as $key => $userr)
                                <form id="demo-form2" role="form" method="POST" action="{{route('ubahPasswordAdmin.update', $userr->id)}}" data-parsley-validate class="form-horizontal form-label-left">
                                     {{ csrf_field() }}
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="name">Nama<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="name" required="required" class="form-control col-md-7 col-xs-12" name="name" value="{{ $userr->name }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email<span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="email" name="email" required="required" class="form-control col-md-7 col-xs-12" value="{{ $userr->email }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label for="password" class="control-label col-md-3 col-sm-3 col-xs-12">Password</label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input id="password" class="form-control col-md-7 col-xs-12" type="password" name="password">
                                        </div>
                                    </div>
                                    <div class="ln_solid"></div>
                                    <div class="form-group">
                                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                            <button type="submit" class="btn btn-success">Simpan</button>
                                        </div>
                                    </div>
                                </form>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>        
@endsection